### ISSUE TITLE
Need option to turn OFF multiprocessing

### ISSUE THREAD

**Issue by mrbannon** [ELVIS-Project/vis-framework#348]
The multi-processing functionality of vis-framework will not work in Rodan. Can we please have an option to not use it?

(See: https://github.com/ELVIS-Project/vis-framework/commit/4f117f08b7b84fe2a76d5a266515e29b2b53f9d1)

Error:

Traceback (most recent call last):
  File "/home/mrbannon/virtual_environments/rodan-vis/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mrbannon/virtual_environments/rodan-vis/local/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mrbannon/Rodan/rodan/jobs/base.py", line 412, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/home/mrbannon/Rodan/rodan/jobs/vis-rodan/indexers/vertical_interval_indexer.py", line 62, in run_my_task
    vertical_intervals = IntervalIndexer(data, settings).run()
  File "/home/mrbannon/vis-framework/vis/analyzers/indexers/interval.py", line 213, in run
    results = self._do_multiprocessing(combinations)
  File "/home/mrbannon/vis-framework/vis/analyzers/indexer.py", line 346, in _do_multiprocessing
    pool = mp.Pool(cores)
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 124, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children

**Comment by alexandermorgan** [comment]
That's a shame, but ok. I'll make it a setting that defaults to off.
